workflows:
  ios_release:
    name: iOS Release (App Store)
      instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - ios_signing
      vars:
        APP_BUNDLE_IDENTIFIER: "com.cgu.cguTarjeta" # reemplazar si hace falta
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
    scripts:
      - name: Prepare environment
        script: |
          set -e
          flutter --version
          flutter pub get
          cd ios
          pod install --repo-update || pod install
          cd ..
      - name: Build iOS IPA (signed via integration)
        script: |
          set -e
          flutter clean
          # Usamos flutter build ipa; Codemagic gestionar치 el signing si la integraci칩n est치 disponible
          flutter build ipa --release --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        use_credentials_from_integration: true
        distribute_to_testflight: true
        release_notes: "Build desde Codemagic (usando integraci칩n de cuenta)"

  ios_unsigned_build:
    name: iOS Unsigned Build (no publish)
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      vars:
        APP_BUNDLE_IDENTIFIER: "com.cgu.cguTarjeta"
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
    scripts:
      - name: Prepare environment
        script: |
          set -e
          flutter --version
          flutter pub get
          cd ios
          pod install --repo-update || pod install
          cd ..
      - name: Build iOS app (no codesign)
        script: |
          set -e
          flutter clean
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
