workflows:
  ios_release:
    name: iOS Release (App Store)
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Vista South
    environment:
      flutter: stable
      groups:
        - ios_signing
      vars:
        APP_BUNDLE_IDENTIFIER: "com.cgu.cguTarjeta" # reemplazar
        FLUTTER_BUILD_NAME: "1.0.0"
        # FLUTTER_BUILD_NUMBER se genera automáticamente (ver script más abajo)
    scripts:
      - name: Generate automatic build number
        script: |
          set -e
          # Genera un número único basado en timestamp para evitar conflictos
          # Esto asegura un número único para cada build y evita problemas con builds que no llegaron a TestFlight
          # Usa el timestamp completo (segundos desde 1970) para garantizar un número siempre mayor
          TIMESTAMP=$(date +%s)
          # El timestamp actual está en ~1736000000, así que usamos los últimos 9 dígitos
          # Esto garantiza que cada build tenga un número mayor que el anterior
          BUILD_NUMBER=${TIMESTAMP: -9}
          # Elimina el cero inicial si existe para evitar problemas
          BUILD_NUMBER=$((10#$BUILD_NUMBER))
          
          # Asegura que el build number sea mayor que el último usado (6)
          # Si el número generado es menor o igual a 6, ajusta a 7 como mínimo
          LAST_BUILD_NUMBER=6
          if [ "$BUILD_NUMBER" -le "$LAST_BUILD_NUMBER" ]; then
            echo "⚠️  WARNING: Build number generado ($BUILD_NUMBER) es menor o igual al último usado ($LAST_BUILD_NUMBER)"
            BUILD_NUMBER=$((LAST_BUILD_NUMBER + 1))
            echo "✅ Ajustado a: $BUILD_NUMBER"
          fi
          
          # Exportar la variable
          export FLUTTER_BUILD_NUMBER="$BUILD_NUMBER"
          
          # Guardar en CM_ENV para que esté disponible en los siguientes scripts
          echo "FLUTTER_BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV
          
          echo "=========================================="
          echo "🔢 GENERANDO BUILD NUMBER"
          echo "=========================================="
          echo "Timestamp: $TIMESTAMP"
          echo "Build Number generado: $BUILD_NUMBER"
          echo "Último build number usado: $LAST_BUILD_NUMBER"
          echo "Este número es único y mayor que cualquier build anterior"
          echo "=========================================="
          echo ""
          echo "✅ Build number guardado en CM_ENV: FLUTTER_BUILD_NUMBER=$BUILD_NUMBER"
      - name: Set up iOS code signing (Automatic via App Store Connect)
        script: |
          set -e
          keychain initialize
          # Solo obtiene perfiles, NO crea certificados (usa el certificado del usuario)
          app-store-connect fetch-signing-files "$APP_BUNDLE_IDENTIFIER" --type IOS_APP_STORE
      - name: Prepare environment
        script: |
          set -e
          flutter --version
          flutter pub get
          cd ios
          pod install --repo-update || pod install
          cd ..
      - name: Verificar imágenes reales de íconos iOS
        script: |
          set -e
          echo "=========================================="
          echo "🖼️  VERIFICANDO IMÁGENES REALES DE iOS"
          echo "=========================================="
          
          ICON_DIR="ios/Runner/Assets.xcassets/AppIcon.appiconset"
          
          # Verificar que el directorio existe
          if [ ! -d "$ICON_DIR" ]; then
            echo "❌ ERROR: Directorio de íconos no existe: $ICON_DIR"
            exit 1
          fi
          
          # Verificar el ícono CRÍTICO de 1024x1024 (obligatorio para App Store)
          ICON_1024="$ICON_DIR/Icon-App-1024x1024@1x.png"
          echo ""
          echo "🔍 Verificando ícono de 1024x1024 (OBLIGATORIO para App Store)..."
          
          if [ ! -f "$ICON_1024" ]; then
            echo "❌ ERROR: Falta el archivo de imagen: Icon-App-1024x1024@1x.png"
            echo "   Regenerando íconos..."
            flutter pub run flutter_launcher_icons:main
            if [ ! -f "$ICON_1024" ]; then
              echo "❌ ERROR: El ícono de 1024x1024 no se generó correctamente"
              exit 1
            fi
          fi
          
          # Verificar tamaño real de la imagen usando sips (macOS)
          if command -v sips >/dev/null 2>&1; then
            ICON_WIDTH=$(sips -g pixelWidth "$ICON_1024" 2>/dev/null | grep pixelWidth | awk '{print $2}')
            ICON_HEIGHT=$(sips -g pixelHeight "$ICON_1024" 2>/dev/null | grep pixelHeight | awk '{print $2}')
            
            echo "   Tamaño real de la imagen: ${ICON_WIDTH}x${ICON_HEIGHT}"
            
            if [ -z "$ICON_WIDTH" ] || [ -z "$ICON_HEIGHT" ]; then
              echo "❌ ERROR: No se pudo leer las dimensiones de la imagen"
              echo "   El archivo puede estar corrupto o no ser una imagen válida"
              exit 1
            fi
            
            if [ "$ICON_WIDTH" != "1024" ] || [ "$ICON_HEIGHT" != "1024" ]; then
              echo "❌ ERROR: El ícono de 1024x1024 NO tiene el tamaño correcto"
              echo "   Tamaño actual: ${ICON_WIDTH}x${ICON_HEIGHT}"
              echo "   Tamaño requerido: 1024x1024"
              echo "   Regenerando íconos con el tamaño correcto..."
              flutter pub run flutter_launcher_icons:main
              
              # Verificar nuevamente después de regenerar
              ICON_WIDTH=$(sips -g pixelWidth "$ICON_1024" 2>/dev/null | grep pixelWidth | awk '{print $2}')
              ICON_HEIGHT=$(sips -g pixelHeight "$ICON_1024" 2>/dev/null | grep pixelHeight | awk '{print $2}')
              
              if [ "$ICON_WIDTH" != "1024" ] || [ "$ICON_HEIGHT" != "1024" ]; then
                echo "❌ ERROR: El ícono sigue teniendo el tamaño incorrecto después de regenerar"
                echo "   Verifica que el ícono fuente (Android) tenga al menos 1024x1024 píxeles"
                exit 1
              fi
            fi
            
            echo "✅ Ícono de 1024x1024 tiene el tamaño correcto"
            
            # Verificar que la imagen no esté corrupta
            if ! sips -s format png "$ICON_1024" >/dev/null 2>&1; then
              echo "❌ ERROR: La imagen está corrupta o no es un PNG válido"
              exit 1
            fi
            echo "✅ La imagen es válida y no está corrupta"
            
          else
            # Si sips no está disponible, al menos verificar que el archivo existe y tiene tamaño
            FILE_SIZE=$(stat -f%z "$ICON_1024" 2>/dev/null || stat -c%s "$ICON_1024" 2>/dev/null || echo "0")
            if [ "$FILE_SIZE" -lt 1000 ]; then
              echo "⚠️  WARNING: El archivo es muy pequeño (${FILE_SIZE} bytes), puede estar corrupto"
            else
              echo "✅ Archivo existe y tiene tamaño razonable (${FILE_SIZE} bytes)"
            fi
          fi
          
          # Verificar otros íconos importantes
          echo ""
          echo "🔍 Verificando otros íconos requeridos..."
          MISSING_COUNT=0
          
          for icon in \
            "Icon-App-60x60@3x.png" \
            "Icon-App-60x60@2x.png" \
            "Icon-App-40x40@3x.png" \
            "Icon-App-40x40@2x.png" \
            "Icon-App-29x29@3x.png" \
            "Icon-App-29x29@2x.png"; do
            if [ ! -f "$ICON_DIR/$icon" ]; then
              echo "⚠️  Falta: $icon"
              MISSING_COUNT=$((MISSING_COUNT + 1))
            fi
          done
          
          if [ "$MISSING_COUNT" -gt 0 ]; then
            echo "⚠️  Faltan $MISSING_COUNT íconos, regenerando..."
            flutter pub run flutter_launcher_icons:main
          else
            echo "✅ Todos los íconos requeridos están presentes"
          fi
          
          echo ""
          echo "=========================================="
          echo "✅ Verificación de imágenes completada"
          echo "=========================================="
      - name: Select provisioning profiles in the Xcode project
        script: |
          set -e
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          set -e
          # Cargar variables de entorno guardadas
          if [ -f "$CM_ENV" ]; then
            source "$CM_ENV"
          fi
          
          # Verificar que el build number se cargó correctamente
          if [ -z "$FLUTTER_BUILD_NUMBER" ]; then
            echo "❌ ERROR: FLUTTER_BUILD_NUMBER no está definido"
            echo "Generando build number de emergencia..."
            TIMESTAMP=$(date +%s)
            FLUTTER_BUILD_NUMBER=${TIMESTAMP: -9}
            FLUTTER_BUILD_NUMBER=$((10#$FLUTTER_BUILD_NUMBER))
            if [ "$FLUTTER_BUILD_NUMBER" -le 6 ]; then
              FLUTTER_BUILD_NUMBER=7
            fi
            export FLUTTER_BUILD_NUMBER="$FLUTTER_BUILD_NUMBER"
          fi
          
          echo "=========================================="
          echo "🏗️  INFORMACIÓN DE BUILD"
          echo "=========================================="
          echo "Bundle ID: $APP_BUNDLE_IDENTIFIER"
          echo "Build Name (Version): $FLUTTER_BUILD_NAME"
          echo "Build Number que se usará: $FLUTTER_BUILD_NUMBER"
          echo "=========================================="
          echo ""
          echo "Verificando que el build number sea válido..."
          if [ "$FLUTTER_BUILD_NUMBER" -le 6 ]; then
            echo "❌ ERROR: Build number ($FLUTTER_BUILD_NUMBER) debe ser mayor que 6"
            exit 1
          fi
          echo "✅ Build number válido: $FLUTTER_BUILD_NUMBER"
          echo ""
          echo "Limpiando build anterior..."
          flutter clean
          echo ""
          echo "Compilando IPA con build number: $FLUTTER_BUILD_NUMBER"
          echo "Usando: flutter build ipa --release --build-name=\"$FLUTTER_BUILD_NAME\" --build-number=\"$FLUTTER_BUILD_NUMBER\""
          # Forzar que Flutter use el build number especificado, no el del pubspec.yaml
          flutter build ipa \
            --release \
            --build-name="$FLUTTER_BUILD_NAME" \
            --build-number="$FLUTTER_BUILD_NUMBER" \
            --dart-define=FLUTTER_BUILD_NUMBER="$FLUTTER_BUILD_NUMBER"
          
          # Verificar que el build number se aplicó correctamente
          echo ""
          echo "Verificando build number en el IPA generado..."
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ ! -z "$IPA_PATH" ]; then
            unzip -q -o "$IPA_PATH" -d /tmp/ipa_check 2>/dev/null || true
            ACTUAL_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" /tmp/ipa_check/Payload/Runner.app/Info.plist 2>/dev/null || echo "")
            echo "Build number en el IPA: $ACTUAL_BUILD_NUMBER"
            echo "Build number esperado: $FLUTTER_BUILD_NUMBER"
            if [ "$ACTUAL_BUILD_NUMBER" != "$FLUTTER_BUILD_NUMBER" ]; then
              echo "❌ ERROR: El build number en el IPA ($ACTUAL_BUILD_NUMBER) no coincide con el esperado ($FLUTTER_BUILD_NUMBER)"
              exit 1
            fi
            echo "✅ Build number correcto en el IPA"
          fi
          echo ""
          echo "✅ Build completado"
      - name: Verify IPA file
        script: |
          set -e
          echo "Verificando IPA generado..."
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "ERROR: No se encontró el archivo IPA"
            exit 1
          fi
          echo "IPA encontrado: $IPA_PATH"
          ls -lh "$IPA_PATH"
          echo "Tamaño del IPA: $(du -h "$IPA_PATH" | cut -f1)"
      - name: Verify bundle identifier and build number
        script: |
          set -e
          echo "=========================================="
          echo "🔍 VERIFICANDO IPA GENERADO"
          echo "=========================================="
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ ERROR: No se encontró el archivo IPA"
            exit 1
          fi
          echo "IPA encontrado: $IPA_PATH"
          echo ""
          # Extraer el IPA para verificar su contenido
          unzip -q -o "$IPA_PATH" -d /tmp/ipa_extract 2>/dev/null || true
          
          # Verificar Bundle ID
          BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" /tmp/ipa_extract/Payload/Runner.app/Info.plist 2>/dev/null || echo "")
          echo "Bundle ID en el IPA: $BUNDLE_ID"
          echo "Bundle ID esperado: $APP_BUNDLE_IDENTIFIER"
          if [ "$BUNDLE_ID" != "$APP_BUNDLE_IDENTIFIER" ]; then
            echo "❌ ERROR: Bundle ID no coincide"
            exit 1
          fi
          echo "✅ Bundle ID correcto"
          echo ""
          
          # Verificar Build Number
          IPA_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" /tmp/ipa_extract/Payload/Runner.app/Info.plist 2>/dev/null || echo "")
          echo "Build Number en el IPA: $IPA_BUILD_NUMBER"
          echo "Build Number esperado: $FLUTTER_BUILD_NUMBER"
          if [ "$IPA_BUILD_NUMBER" != "$FLUTTER_BUILD_NUMBER" ]; then
            echo "❌ ERROR: Build Number no coincide"
            echo "   El IPA tiene: $IPA_BUILD_NUMBER"
            echo "   Se esperaba: $FLUTTER_BUILD_NUMBER"
            exit 1
          fi
          echo "✅ Build Number correcto"
          echo ""
          echo "Verificando que el build number sea mayor que el último usado..."
          LAST_BUILD_NUMBER=6
          if [ "$IPA_BUILD_NUMBER" -le "$LAST_BUILD_NUMBER" ]; then
            echo "❌ ERROR: Build Number ($IPA_BUILD_NUMBER) debe ser mayor que $LAST_BUILD_NUMBER"
            exit 1
          fi
          echo "✅ Build Number es mayor que el último usado ($LAST_BUILD_NUMBER)"
          echo "=========================================="
      - name: Verificar estado después del upload
        script: |
          set -e
          echo "=========================================="
          echo "🔍 DIAGNÓSTICO POST-UPLOAD"
          echo "=========================================="
          echo ""
          echo "📦 Bundle ID: $APP_BUNDLE_IDENTIFIER"
          echo "📱 Versión: $FLUTTER_BUILD_NAME"
          echo "🔢 Build Number: $FLUTTER_BUILD_NUMBER"
          echo ""
          echo "✅ UPLOAD EXITOSO - El IPA se subió a App Store Connect"
          echo "✅ La app EXISTE en App Store Connect (ID: 6754770379)"
          echo ""
          echo "=========================================="
          echo "📍 VERIFICAR EN APP STORE CONNECT:"
          echo "=========================================="
          echo ""
          echo "1️⃣  Ve a: https://appstoreconnect.apple.com/apps/6754770379"
          echo "    (Tu app: App de Tarjeta Digital)"
          echo ""
          echo "2️⃣  Clic en la pestaña 'TESTFLIGHT' (no en 'App Store')"
          echo ""
          echo "3️⃣  Busca el build número: $FLUTTER_BUILD_NUMBER"
          echo "    Versión: $FLUTTER_BUILD_NAME"
          echo ""
          echo "4️⃣  Estados posibles del build:"
          echo "    ⏳ 'Procesando' = Apple está validando (ESPERA 30-60 minutos)"
          echo "    ✅ 'Listo para probar' = Build disponible en TestFlight"
          echo "    ❌ 'Problema de procesamiento' = HAY UN ERROR (revisa detalles)"
          echo "    ⏸️  'Expirado' = Build antiguo que ya no se puede usar"
          echo ""
          echo "5️⃣  Si el build NO aparece:"
          echo "    a) Espera al menos 30-60 minutos (Apple necesita procesar)"
          echo "    b) Revisa la sección 'ACTIVITY' (abajo en TestFlight)"
          echo "    c) Revisa el email: vitomuzio02@gmail.com"
          echo "    d) Verifica que el build number sea ÚNICO (no duplicado)"
          echo ""
          echo "6️⃣  Si aparece 'Problema de procesamiento':"
          echo "    - Lee el mensaje de error específico"
          echo "    - Puede ser problema de código, certificados, o configuración"
          echo ""
          echo "=========================================="
          echo "📧 Email: vitomuzio02@gmail.com"
          echo "   (Apple envía notificaciones cuando el build esté listo o haya errores)"
          echo "=========================================="
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "vitomuzio02@gmail.com"  # TODO: Agrega tu email aquí para recibir notificaciones
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        # CRÍTICO: Subir a TestFlight automáticamente
        submit_to_testflight: true
        # Notificar a grupos beta (opcional - comenta si no usas grupos)
        # beta_groups:
        #   - group name 1
        # Enviar notificaciones por email cuando el build esté listo
        notify: true
        # IMPORTANTE: No descomentar esto hasta que TestFlight funcione
        # submit_to_app_store: true
        # Si los builds no aparecen, descomenta las siguientes líneas para debug
        # force: true  # Fuerza re-subir aunque ya exista
        # skip_waiting_for_build_processing: false  # Espera el procesamiento completo
