workflows:
  ios_release:
    name: iOS Release (App Store)
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Vista South
    environment:
      flutter: stable
      groups:
        - ios_signing
      vars:
        APP_BUNDLE_IDENTIFIER: "com.cgu.cguTarjeta" # reemplazar
        FLUTTER_BUILD_NAME: "1.0.0"
        # FLUTTER_BUILD_NUMBER se genera automáticamente (ver script más abajo)
    scripts:
      - name: Generate automatic build number
        script: |
          set -e
          # Usa el número de build de Codemagic si está disponible
          if [ -n "$CM_BUILD_NUMBER" ]; then
            export FLUTTER_BUILD_NUMBER="$CM_BUILD_NUMBER"
            echo "Usando número de build de Codemagic: $FLUTTER_BUILD_NUMBER"
          else
            # Genera un número único basado en timestamp (segundos desde epoch)
            # Esto asegura un número único para cada build
            BUILD_NUMBER=$(date +%s)
            # Toma solo los últimos 8 dígitos para que sea más manejable (max ~99999999)
            BUILD_NUMBER=${BUILD_NUMBER: -8}
            export FLUTTER_BUILD_NUMBER="$BUILD_NUMBER"
            echo "Generado número de build basado en timestamp: $FLUTTER_BUILD_NUMBER"
          fi
          # Guarda la variable para que esté disponible en los siguientes scripts
          echo "FLUTTER_BUILD_NUMBER=$FLUTTER_BUILD_NUMBER" >> $CM_ENV
          echo "Build number configurado: $FLUTTER_BUILD_NUMBER"
      - name: Set up iOS code signing (Automatic via App Store Connect)
        script: |
          set -e
          keychain initialize
          # Solo obtiene perfiles, NO crea certificados (usa el certificado del usuario)
          app-store-connect fetch-signing-files "$APP_BUNDLE_IDENTIFIER" --type IOS_APP_STORE
      - name: Prepare environment
        script: |
          set -e
          flutter --version
          flutter pub get
          cd ios
          pod install --repo-update || pod install
          cd ..
      - name: Select provisioning profiles in the Xcode project
        script: |
          set -e
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          set -e
          echo "=== Información de Build ==="
          echo "Bundle ID: $APP_BUNDLE_IDENTIFIER"
          echo "Build Name (Version): $FLUTTER_BUILD_NAME"
          echo "Build Number: $FLUTTER_BUILD_NUMBER"
          echo "============================"
          flutter clean
          flutter build ipa \
            --release \
            --build-name="$FLUTTER_BUILD_NAME" \
            --build-number="$FLUTTER_BUILD_NUMBER"
      - name: Verify IPA file
        script: |
          set -e
          echo "Verificando IPA generado..."
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "ERROR: No se encontró el archivo IPA"
            exit 1
          fi
          echo "IPA encontrado: $IPA_PATH"
          ls -lh "$IPA_PATH"
          echo "Tamaño del IPA: $(du -h "$IPA_PATH" | cut -f1)"
      - name: Verify bundle identifier
        script: |
          set -e
          echo "Verificando Bundle ID..."
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          unzip -q -o "$IPA_PATH" -d /tmp/ipa_extract 2>/dev/null || true
          BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" /tmp/ipa_extract/Payload/Runner.app/Info.plist 2>/dev/null || echo "")
          echo "Bundle ID en el IPA: $BUNDLE_ID"
          echo "Bundle ID esperado: $APP_BUNDLE_IDENTIFIER"
          if [ "$BUNDLE_ID" != "$APP_BUNDLE_IDENTIFIER" ]; then
            echo "WARNING: Bundle ID no coincide"
          fi
      - name: Verificar estado después del upload
        script: |
          set -e
          echo "=========================================="
          echo "🔍 DIAGNÓSTICO POST-UPLOAD"
          echo "=========================================="
          echo ""
          echo "📦 Bundle ID: $APP_BUNDLE_IDENTIFIER"
          echo "📱 Versión: $FLUTTER_BUILD_NAME"
          echo "🔢 Build Number: $FLUTTER_BUILD_NUMBER"
          echo ""
          echo "✅ UPLOAD EXITOSO - El IPA se subió a App Store Connect"
          echo ""
          echo "=========================================="
          echo "🚨 PROBLEMA CONOCIDO: Build no aparece en TestFlight"
          echo "=========================================="
          echo ""
          echo "CAUSA MÁS PROBABLE: La app NO existe en App Store Connect"
          echo ""
          echo "SOLUCIÓN PASO A PASO:"
          echo ""
          echo "1️⃣  Ve a: https://appstoreconnect.apple.com/apps"
          echo ""
          echo "2️⃣  Verifica si existe una app con Bundle ID: $APP_BUNDLE_IDENTIFIER"
          echo ""
          echo "3️⃣  Si NO existe, CREA LA APP:"
          echo "    - Clic en '+ NUEVA APP' o 'Crear'"
          echo "    - Selecciona la plataforma: iOS"
          echo "    - Nombre: 'CGU Tarjeta Digital' (o el que prefieras)"
          echo "    - Idioma primario: Español"
          echo "    - Bundle ID: $APP_BUNDLE_IDENTIFIER"
          echo "    - SKU: Usa algo único como 'cgutarjetadigital001'"
          echo ""
          echo "4️⃣  DESPUÉS de crear la app:"
          echo "    - Ejecuta OTRA compilación en Codemagic"
          echo "    - El build DEBERÍA aparecer en TestFlight"
          echo ""
          echo "5️⃣  Si la app YA EXISTE pero el build no aparece:"
          echo "    - Verifica que el Bundle ID sea EXACTAMENTE: $APP_BUNDLE_IDENTIFIER"
          echo "    - Ve a: App Store Connect > Tu App > TestFlight"
          echo "    - Espera 30-60 minutos (Apple procesa el build)"
          echo "    - Revisa si hay errores en la sección 'Activity'"
          echo ""
          echo "=========================================="
          echo "📧 También revisa: vitomuzio02@gmail.com"
          echo "   (Apple envía notificaciones sobre el estado del build)"
          echo "=========================================="
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "vitomuzio02@gmail.com"  # TODO: Agrega tu email aquí para recibir notificaciones
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        # CRÍTICO: Subir a TestFlight automáticamente
        submit_to_testflight: true
        # Notificar a grupos beta (opcional - comenta si no usas grupos)
        # beta_groups:
        #   - group name 1
        # Enviar notificaciones por email cuando el build esté listo
        notify: true
        # IMPORTANTE: No descomentar esto hasta que TestFlight funcione
        # submit_to_app_store: true
