workflows:
  ios_release:
    name: iOS Release (App Store)
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Vista South
    environment:
      flutter: stable
      groups:
        - ios_signing
      vars:
        APP_BUNDLE_IDENTIFIER: "com.cgu.cguTarjeta" # reemplazar
        FLUTTER_BUILD_NAME: "1.0.0"
        # FLUTTER_BUILD_NUMBER se genera automáticamente (ver script más abajo)
    scripts:
      - name: Generate automatic build number
        script: |
          set -e
          # Genera un número único basado en timestamp para evitar conflictos
          # Esto asegura un número único para cada build y evita problemas con builds que no llegaron a TestFlight
          # Usa el timestamp completo (segundos desde 1970) para garantizar un número siempre mayor
          TIMESTAMP=$(date +%s)
          # El timestamp actual está en ~1736000000, así que usamos los últimos 9 dígitos
          # Esto garantiza que cada build tenga un número mayor que el anterior
          BUILD_NUMBER=${TIMESTAMP: -9}
          # Elimina el cero inicial si existe para evitar problemas
          BUILD_NUMBER=$((10#$BUILD_NUMBER))
          
          # Asegura que el build number sea mayor que el último usado (6)
          # Si el número generado es menor o igual a 6, suma 1000 para asegurar que sea mayor
          LAST_BUILD_NUMBER=6
          if [ "$BUILD_NUMBER" -le "$LAST_BUILD_NUMBER" ]; then
            echo "⚠️  WARNING: Build number generado ($BUILD_NUMBER) es menor o igual al último usado ($LAST_BUILD_NUMBER)"
            BUILD_NUMBER=$((LAST_BUILD_NUMBER + 1))
            echo "✅ Ajustado a: $BUILD_NUMBER"
          fi
          
          export FLUTTER_BUILD_NUMBER="$BUILD_NUMBER"
          echo "=========================================="
          echo "🔢 GENERANDO BUILD NUMBER"
          echo "=========================================="
          echo "Timestamp: $TIMESTAMP"
          echo "Build Number generado: $FLUTTER_BUILD_NUMBER"
          echo "Último build number usado: $LAST_BUILD_NUMBER"
          echo "Este número es único y mayor que cualquier build anterior"
          echo "=========================================="
          # Guarda la variable para que esté disponible en los siguientes scripts
          echo "FLUTTER_BUILD_NUMBER=$FLUTTER_BUILD_NUMBER" >> $CM_ENV
      - name: Set up iOS code signing (Automatic via App Store Connect)
        script: |
          set -e
          keychain initialize
          # Solo obtiene perfiles, NO crea certificados (usa el certificado del usuario)
          app-store-connect fetch-signing-files "$APP_BUNDLE_IDENTIFIER" --type IOS_APP_STORE
      - name: Prepare environment
        script: |
          set -e
          flutter --version
          flutter pub get
          cd ios
          pod install --repo-update || pod install
          cd ..
      - name: Select provisioning profiles in the Xcode project
        script: |
          set -e
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          set -e
          # Verificar que el build number se cargó correctamente
          if [ -z "$FLUTTER_BUILD_NUMBER" ]; then
            echo "ERROR: FLUTTER_BUILD_NUMBER no está definido"
            exit 1
          fi
          echo "=========================================="
          echo "🏗️  INFORMACIÓN DE BUILD"
          echo "=========================================="
          echo "Bundle ID: $APP_BUNDLE_IDENTIFIER"
          echo "Build Name (Version): $FLUTTER_BUILD_NAME"
          echo "Build Number: $FLUTTER_BUILD_NUMBER"
          echo "=========================================="
          echo ""
          echo "Limpiando build anterior..."
          flutter clean
          echo ""
          echo "Compilando IPA con build number: $FLUTTER_BUILD_NUMBER"
          flutter build ipa \
            --release \
            --build-name="$FLUTTER_BUILD_NAME" \
            --build-number="$FLUTTER_BUILD_NUMBER"
          echo ""
          echo "✅ Build completado"
      - name: Verify IPA file
        script: |
          set -e
          echo "Verificando IPA generado..."
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "ERROR: No se encontró el archivo IPA"
            exit 1
          fi
          echo "IPA encontrado: $IPA_PATH"
          ls -lh "$IPA_PATH"
          echo "Tamaño del IPA: $(du -h "$IPA_PATH" | cut -f1)"
      - name: Verify bundle identifier and build number
        script: |
          set -e
          echo "=========================================="
          echo "🔍 VERIFICANDO IPA GENERADO"
          echo "=========================================="
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -1)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ ERROR: No se encontró el archivo IPA"
            exit 1
          fi
          echo "IPA encontrado: $IPA_PATH"
          echo ""
          # Extraer el IPA para verificar su contenido
          unzip -q -o "$IPA_PATH" -d /tmp/ipa_extract 2>/dev/null || true
          
          # Verificar Bundle ID
          BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" /tmp/ipa_extract/Payload/Runner.app/Info.plist 2>/dev/null || echo "")
          echo "Bundle ID en el IPA: $BUNDLE_ID"
          echo "Bundle ID esperado: $APP_BUNDLE_IDENTIFIER"
          if [ "$BUNDLE_ID" != "$APP_BUNDLE_IDENTIFIER" ]; then
            echo "❌ ERROR: Bundle ID no coincide"
            exit 1
          fi
          echo "✅ Bundle ID correcto"
          echo ""
          
          # Verificar Build Number
          IPA_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" /tmp/ipa_extract/Payload/Runner.app/Info.plist 2>/dev/null || echo "")
          echo "Build Number en el IPA: $IPA_BUILD_NUMBER"
          echo "Build Number esperado: $FLUTTER_BUILD_NUMBER"
          if [ "$IPA_BUILD_NUMBER" != "$FLUTTER_BUILD_NUMBER" ]; then
            echo "❌ ERROR: Build Number no coincide"
            echo "   El IPA tiene: $IPA_BUILD_NUMBER"
            echo "   Se esperaba: $FLUTTER_BUILD_NUMBER"
            exit 1
          fi
          echo "✅ Build Number correcto"
          echo ""
          echo "Verificando que el build number sea mayor que el último usado..."
          LAST_BUILD_NUMBER=6
          if [ "$IPA_BUILD_NUMBER" -le "$LAST_BUILD_NUMBER" ]; then
            echo "❌ ERROR: Build Number ($IPA_BUILD_NUMBER) debe ser mayor que $LAST_BUILD_NUMBER"
            exit 1
          fi
          echo "✅ Build Number es mayor que el último usado ($LAST_BUILD_NUMBER)"
          echo "=========================================="
      - name: Verificar estado después del upload
        script: |
          set -e
          echo "=========================================="
          echo "🔍 DIAGNÓSTICO POST-UPLOAD"
          echo "=========================================="
          echo ""
          echo "📦 Bundle ID: $APP_BUNDLE_IDENTIFIER"
          echo "📱 Versión: $FLUTTER_BUILD_NAME"
          echo "🔢 Build Number: $FLUTTER_BUILD_NUMBER"
          echo ""
          echo "✅ UPLOAD EXITOSO - El IPA se subió a App Store Connect"
          echo "✅ La app EXISTE en App Store Connect (ID: 6754770379)"
          echo ""
          echo "=========================================="
          echo "📍 VERIFICAR EN APP STORE CONNECT:"
          echo "=========================================="
          echo ""
          echo "1️⃣  Ve a: https://appstoreconnect.apple.com/apps/6754770379"
          echo "    (Tu app: App de Tarjeta Digital)"
          echo ""
          echo "2️⃣  Clic en la pestaña 'TESTFLIGHT' (no en 'App Store')"
          echo ""
          echo "3️⃣  Busca el build número: $FLUTTER_BUILD_NUMBER"
          echo "    Versión: $FLUTTER_BUILD_NAME"
          echo ""
          echo "4️⃣  Estados posibles del build:"
          echo "    ⏳ 'Procesando' = Apple está validando (ESPERA 30-60 minutos)"
          echo "    ✅ 'Listo para probar' = Build disponible en TestFlight"
          echo "    ❌ 'Problema de procesamiento' = HAY UN ERROR (revisa detalles)"
          echo "    ⏸️  'Expirado' = Build antiguo que ya no se puede usar"
          echo ""
          echo "5️⃣  Si el build NO aparece:"
          echo "    a) Espera al menos 30-60 minutos (Apple necesita procesar)"
          echo "    b) Revisa la sección 'ACTIVITY' (abajo en TestFlight)"
          echo "    c) Revisa el email: vitomuzio02@gmail.com"
          echo "    d) Verifica que el build number sea ÚNICO (no duplicado)"
          echo ""
          echo "6️⃣  Si aparece 'Problema de procesamiento':"
          echo "    - Lee el mensaje de error específico"
          echo "    - Puede ser problema de código, certificados, o configuración"
          echo ""
          echo "=========================================="
          echo "📧 Email: vitomuzio02@gmail.com"
          echo "   (Apple envía notificaciones cuando el build esté listo o haya errores)"
          echo "=========================================="
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "vitomuzio02@gmail.com"  # TODO: Agrega tu email aquí para recibir notificaciones
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        # CRÍTICO: Subir a TestFlight automáticamente
        submit_to_testflight: true
        # Notificar a grupos beta (opcional - comenta si no usas grupos)
        # beta_groups:
        #   - group name 1
        # Enviar notificaciones por email cuando el build esté listo
        notify: true
        # IMPORTANTE: No descomentar esto hasta que TestFlight funcione
        # submit_to_app_store: true
        # Si los builds no aparecen, descomenta las siguientes líneas para debug
        # force: true  # Fuerza re-subir aunque ya exista
        # skip_waiting_for_build_processing: false  # Espera el procesamiento completo
