workflows:
  ios_release:
    name: iOS Release (App Store)
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Vista South
    environment:
      flutter: stable
      vars:
        APP_BUNDLE_IDENTIFIER: "com.cgu.cguTarjeta" # reemplazar
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
    scripts:
      - name: Prepare environment
        script: |
          set -e
          flutter --version
          flutter pub get
          cd ios
          pod install --repo-update || pod install
          cd ..
      - name: Build iOS IPA
        script: |
          set -e
          flutter clean
          flutter build ipa --release --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
